'use client';

import { useState, useEffect } from 'react';
import {
  ChakraProvider,
  Box,
  Flex,
  Heading,
  Text,
  Button,
  Spinner,
  Alert,
  AlertIcon,
  VStack
} from '@chakra-ui/react';
import { Tournament, Saint } from '@/types';
import { saintfestTheme } from '@/lib/chakra-theme';
import Navigation from '@/components/Navigation';
import TournamentBracket from '@/components/tournament/TournamentBracket';
import { getActivePublishedBracket } from '@/lib/tournamentService';

export default function PublicBracketPage() {
  const [publishedTournament, setPublishedTournament] = useState<Tournament | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>('');

  useEffect(() => {
    loadPublishedBracket();
  }, []);

  const loadPublishedBracket = async () => {
    try {
      console.log('Fetching published tournament for year 2025...');
      const publishedBracket = await getActivePublishedBracket(2025);

      console.log('Retrieved published bracket:', publishedBracket);

      if (publishedBracket) {
        // Helper function to derive categoryKey from category name
        const getCategoryKey = (categoryName: string): keyof Saint => {
          const lowerName = categoryName.toLowerCase().replace(/\s+/g, '');
          switch (lowerName) {
            case 'martyrs': return 'martyrs';
            case 'doctorsofthechurch': return 'doctorsofthechurch';
            case 'confessors': return 'confessors';
            case 'abbots&abbesses':
            case 'abbotabbess': return 'abbotabbess';
            case 'evangelists': return 'evangelist';
            case 'virgin&widows':
            case 'virginwidows':
            case 'virgins': return 'virgins';
            default: return 'martyrs'; // fallback
          }
        };

        // Convert PublishedBracket back to Tournament format for TournamentBracket component
        const tournament: Tournament = {
          id: publishedBracket.id,
          year: publishedBracket.year,
          title: publishedBracket.title,
          categories: publishedBracket.categories.map(cat => ({
            id: cat.id,
            name: cat.name,
            categoryKey: getCategoryKey(cat.name),
            color: cat.color,
            position: cat.position,
            saints: cat.saints.map(saint => ({
              id: `saint-${saint.name}`, // Generate ID since we only have name
              name: saint.name,
              displayName: saint.name,
              seed: saint.seed,
              popularityScore: 50, // Default value
              eliminated: false,
              // Add other optional Tournament saint fields as needed
            }))
          })),
          rounds: [], // We'll populate this from matches
          status: 'published' as const,
          createdAt: publishedBracket.publishedAt,
          autoGeneratedOn: publishedBracket.publishedAt,
          colorPalette: publishedBracket.colorPalette,
          metadata: {
            totalSaints: 32,
            categoriesUsed: publishedBracket.categories.map(cat => cat.name),
            selectionMethod: 'manual',
            generationTime: 0,
            textMeasurements: {
              longestName: '',
              maxTextWidth: 0,
              maxTextHeight: 0,
            },
            bracketDimensions: {
              totalWidth: publishedBracket.dimensions.totalWidth,
              totalHeight: publishedBracket.dimensions.totalHeight,
              scaleFactor: 1,
            }
          }
        };

        setPublishedTournament(tournament);
      } else {
        console.log('No tournament returned from getActivePublishedBracket');
        setError('No published tournament found for 2025');
      }
    } catch (err) {
      console.error('Failed to load published tournament:', err);
      setError('Failed to load tournament data');
    } finally {
      setLoading(false);
    }
  };

  const downloadBracket = async () => {
    if (!publishedTournament) return;
    // TODO: Implement client-side PDF generation or alternative download method
    alert('PDF download feature will be implemented in a future update.');
  };

  const shareBracket = async () => {
    if (!publishedTournament) return;
    const url = `${window.location.origin}/bracket`;
    try {
      await navigator.share({
        title: `Saintfest ${publishedTournament.year} Bracket`,
        text: 'Check out this March Madness style saint tournament!',
        url: url,
      });
    } catch (error) {
      // Fallback to copying to clipboard
      navigator.clipboard.writeText(url);
      alert('Bracket URL copied to clipboard!');
    }
  };

  if (loading) {
    return (
      <ChakraProvider theme={saintfestTheme}>
        <Box minH="100vh" bg="cream.50" display="flex" alignItems="center" justifyContent="center">
          <VStack spacing={4}>
            <Spinner size="xl" color="saintfest.500" thickness="4px" />
            <Text fontFamily="var(--font-cormorant)" fontSize="lg" color="gray.600">
              Loading bracket...
            </Text>
          </VStack>
        </Box>
      </ChakraProvider>
    );
  }

  if (error) {
    return (
      <ChakraProvider theme={saintfestTheme}>
        <Box minH="100vh" bg="cream.50" display="flex" alignItems="center" justifyContent="center" p={6}>
          <Alert status="error" maxW="md" borderRadius="lg">
            <AlertIcon />
            <Text>{error}</Text>
          </Alert>
        </Box>
      </ChakraProvider>
    );
  }

  return (
    <ChakraProvider theme={saintfestTheme}>
      <Box minH="100vh" bg="cream.50">
        {/* Header */}
        <Box
          as="header"
          position="sticky"
          top={0}
          zIndex={1000}
          w="100%"
          bg="saintfest.500"
          py={4}
          mb={8}
          boxShadow="sm"
        >
          <Box maxW="64rem" mx="auto" px={6}>
            <Flex justify="space-between" align="center">
              <Heading
                as="a"
                href="/"
                fontSize="4xl"
                fontFamily="var(--font-sorts-mill)"
                color="white"
                textDecoration="none"
                fontWeight="600"
                textShadow="0 1px 2px rgba(0,0,0,0.1)"
                _hover={{ textDecoration: 'none' }}
              >
                Saintfest
              </Heading>

              <Navigation />
            </Flex>
          </Box>
        </Box>

        <Box as="main">
          {publishedTournament ? (
            <VStack spacing={8}>
              {/* Tournament Bracket Display - Same component as admin preview */}
              <TournamentBracket tournament={publishedTournament} />

              {/* Download PDF Button */}
              <Box textAlign="center" py={8}>
                <Button
                  onClick={downloadBracket}
                  size="lg"
                  bg="saintfest.500"
                  color="white"
                  px={8}
                  py={4}
                  fontSize="lg"
                  fontFamily="var(--font-league-spartan)"
                  textTransform="uppercase"
                  letterSpacing="wide"
                  fontWeight="600"
                  borderRadius="lg"
                  boxShadow="lg"
                  _hover={{
                    bg: 'saintfest.600',
                    transform: 'translateY(-2px)',
                    boxShadow: 'xl'
                  }}
                  _active={{
                    transform: 'translateY(0)'
                  }}
                  transition="all 0.2s"
                >
                  📄 Download Printable Bracket PDF
                </Button>
                <Text
                  mt={3}
                  fontSize="sm"
                  color="gray.500"
                  fontFamily="var(--font-cormorant)"
                >
                  Perfect for printing and filling out your predictions!
                </Text>
              </Box>
            </VStack>
          ) : (
            /* Coming Soon Message */
            <Box textAlign="center" maxW="48rem" mx="auto" px={6} py={12}>
              <VStack spacing={12}>
                <VStack spacing={6}>
                  <Heading
                    fontSize="5xl"
                    fontFamily="var(--font-sorts-mill)"
                    color="gray.700"
                    fontWeight="600"
                  >
                    2025 Saintfest Bracket
                  </Heading>
                  <Box w="24" h="1px" bg="gray.300" />
                </VStack>

                <VStack spacing={6}>
                  <Heading
                    fontSize="3xl"
                    fontFamily="var(--font-sorts-mill)"
                    color="gray.700"
                    fontWeight="600"
                  >
                    Announcement Coming Soon!
                  </Heading>
                  <Text
                    fontFamily="var(--font-cormorant)"
                    fontSize="lg"
                    lineHeight="tall"
                    color="gray.500"
                    maxW="32rem"
                  >
                    The 2025 Saintfest bracket will be announced soon.
                    <br />
                    Until then, explore our community posts and learn about past tournaments!
                  </Text>
                </VStack>

                <Button
                  as="a"
                  href="/posts/"
                  bg="saintfest.500"
                  color="white"
                  px={6}
                  py={3}
                  borderRadius="md"
                  fontFamily="var(--font-league-spartan)"
                  textTransform="uppercase"
                  letterSpacing="wide"
                  fontWeight="600"
                  fontSize="sm"
                  _hover={{
                    bg: 'saintfest.600',
                    textDecoration: 'none'
                  }}
                >
                  Read Latest Posts
                </Button>
              </VStack>
            </Box>
          )}
        </Box>

        <Box
          as="footer"
          borderTop="1px solid"
          borderColor="gray.200"
          py={16}
          mt={16}
        >
          <Box maxW="48rem" mx="auto" px={6} textAlign="center">
            <Text
              fontSize="xs"
              fontFamily="var(--font-league-spartan)"
              textTransform="uppercase"
              letterSpacing="wide"
              color="gray.400"
            >
              © 2024 Saintfest · A celebration of saints through community
            </Text>
          </Box>
        </Box>
      </Box>
    </ChakraProvider>
  );
}