name: Deploy to Firebase Hosting

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci

    - name: Security Audit
      run: npm audit --audit-level=moderate
      continue-on-error: false

    - name: Type Check
      run: npm run type-check

    - name: Lint Code
      run: npm run lint

    - name: Build Next.js Application
      run: npm run build:firebase
      env:
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}

    - name: Install Functions Dependencies
      run: |
        cd functions
        npm install

    - name: Verify Functions Structure
      run: |
        echo "Checking functions directory structure..."
        ls -la functions/
        echo "Checking for required files..."
        test -f functions/package.json && echo "✓ package.json found" || echo "✗ package.json missing"
        test -f functions/index.js && echo "✓ index.js found" || echo "✗ index.js missing"

    - name: Deploy to Firebase Functions (Preview)
      if: github.event_name == 'pull_request'
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAINTFESTCODE }}' > ${HOME}/gcloud-service-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
        npx firebase-tools@latest deploy --only functions --project saintfestcode

    - name: Deploy to Firebase Functions (Production)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAINTFESTCODE }}' > ${HOME}/gcloud-service-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
        npx firebase-tools@latest deploy --only functions --project saintfestcode